### ISSUE TITLE
Wrong after installation

### ISSUE THREAD

**Issue by iiiusky** [huclengyue/FlutterToast#1]
`Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.`

**Comment by appdev** [comment]
It seems to be a problem with the Swift version being incompatible. We normally try to use OC again. Are you running the example normal?

**Comment by appdev** [comment]
you can use new version
```
toast: ^0.1.0
```
