### ISSUE TITLE
toast 页面不能穿透事件,导致层级较低的UI界面无法响应事件,会有等待时间,有较大的体验问题

### ISSUE THREAD

**Issue by TPQuietBro** [huclengyue/FlutterToast#18]
这里提出一个简单的优化方案,实测有效: 在Material外层包裹一个IgnorePointer即可.
@override
  Widget build(BuildContext context) {
    return new Positioned(
        top: gravity == 2 ? 50 : null,
        bottom: gravity == 0 ? 50 : null,
        child: IgnorePointer(
          child: Material(
          color: Colors.transparent,
          child: widget,
        )
        ));
  }

**Comment by appdev** [comment]
感谢，之前发布后，很久没有继续关注 flutter了。现在又要重操旧业了。
