### ISSUE TITLE
Toast iOS Error 

### ISSUE THREAD

**Issue by rlecheta** [huclengyue/FlutterToast#2]
Hi, I got this error after running this line:
Toast.show("Toast plugin app", duration: Toast.LENGTH_SHORT, gravity:  Toast.BOTTOM);
--
flutter/.pub-cache/hosted/pub.dartlang.org/toast-0.0.6/ios/Classes/ToastReference.swift:325:37: error: 'init(style:)' has been renamed to 'init(activityIndicatorStyle:)'
            let activityIndicatorView = UIActivityIndicatorView(style: .whiteLarge)
                                        ^                       ~~~~~
                                                                activityIndicatorStyle
    UIKit.UIActivityIndicatorView:6:12: note: 'init(style:)' was introduced in Swift 4.2
        public init(style: UIActivityIndicatorViewStyle)
               ^
    /Users/rlecheta/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/toast-0.0.6/ios/Classes/ToastReference.swift:354:47: error: 'common' has been renamed to 'RunLoopMode.commonModes'
                RunLoop.main.add(timer, forMode: .common)
                                                  ^~~~~~
                                                  RunLoopMode.commonModes
    Foundation.RunLoop.Mode:9:23: note: 'common' was introduced in Swift 4.2
        public static let common: RunLoopMode
                          ^
    /Users/rlecheta/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/toast-0.0.6/ios/Classes/ToastReference.swift:354:47: error: 'common' has been renamed to 'RunLoopMode.commonModes'
                RunLoop.main.add(timer, forMode: .common)
                                                  ^~~~~~
                                                  RunLoopMode.commonModes
    Foundation.RunLoop.Mode:9:23: note: 'common' was introduced in Swift 4.2
        public static let common: RunLoopMode

**Comment by appdev** [comment]
you can use new version
```
toast: ^0.1.0
```
