### ISSUE TITLE
Target of URI doesn't exist: 'package:toast/toast.dart'.

### ISSUE THREAD

**Issue by udarakalpana** [huclengyue/FlutterToast#24]
After Add import **'package:toast/toast.dart';** this line into my main.dart file, not run to my app and show this error message..Please give me a solution how to solve it..

**Error message : Target of URI doesn't exist: 'package:toast/toast.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.**

**Comment by peterhijma** [comment]
You've got to install it first... ? 🤦

**Comment by udarakalpana** [comment]
When find this bug, I had installed it in my project.After restart my IDE(VS Code) It was ok.
