### ISSUE TITLE
null safe support

### ISSUE THREAD

**Issue by anshul** [huclengyue/FlutterToast#28]
This is already null safe as far as I can tell.  Can you please release this with a null safe tag on pub.dev?

**Comment by venkata-reddy-dev** [comment]
@anshul  As you said this package migrated already. but i am not sut why author not yet published into 
                 pub.dev

### please add dependency like below for null safety version support 

```
  toast:
    git:
      url: https://github.com/appdev/FlutterToast.git
```

**Comment by venkata-reddy-dev** [comment]
@appdev  Can you please publish **null safety verision** to pub.dev

**Comment by anshul** [comment]
@appdev  any update?

**Comment by TungPT95** [comment]
@appdev any updates?

**Comment by ahmetbayirli** [comment]
+1

**Comment by jaumard** [comment]
Would be nice to have this on pub.dev please @appdev

**Comment by champ96k** [comment]
Hello everyone can you please assign me, I would love to take it

**Comment by fedecarroz** [comment]
@appdev it would be great to find the null safety check on pub.dev, thank you in advance

**Comment by ghost** [comment]
Hello @appdev, would be nice to have the null safety version on pub.dev

**Comment by appdev** [comment]
It already supports null security

**Comment by appdev** [comment]
Oh! I will fix it soon!
