### ISSUE TITLE
There is a bug that does not disappear after once viewed toast on Android.

### ISSUE THREAD

**Issue by kyungjoongo** [huclengyue/FlutterToast#3]
There is a bug that does not disappear after once viewed toast on Android.

**Comment by appdev** [comment]
you can use last version
```
toast: ^0.1.3
```

**Comment by hahn** [comment]
helo, i'm using latest version (0.1.5), but this bug still exist in ios. how to make toast disappear? thanks

**Comment by appdev** [comment]
Can you show your test code?
