### ISSUE TITLE
Keyboard is over Toast

### ISSUE THREAD

**Issue by freddydrodev** [huclengyue/FlutterToast#8]
Hi there! Thanks for this awesome Flutter plugin. I am actually facing an issue while using it, when I am using Toast.Bottom as gravity value the Keyboard hide the Toast when it is active. can you make the Toast move just above it. I am actually using the center mode but it is not what I initially wanted. Thanks

**Comment by appdev** [comment]
There is currently no way, because FlutterToast uses `OverlayEntry` and cannot be displayed on top of other apps.
